name: CMake

on:
  push:
  pull_request:
  release:
    types: [created]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{matrix.board}}
    strategy:
      matrix:
        include:
          - board: galactic
          - board: cosmic
          - board: stellar

    runs-on: ubuntu-latest

    env:
      PICO_SDK_PATH: $GITHUB_WORKSPACE/pico-sdk
      PIMORONI_PICO_LIBS: $GITHUB_WORKSPACE/pimoroni-pico
      RELEASE_FILE: ${{matrix.board}}-${{github.event.repository.name}}-${{github.event.release.tag_name || github.sha}}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        path: project

    # Checkout the Pimoroni Pico Libraries
    - name: Checkout Pimoroni Pico Libraries
      uses: actions/checkout@v4
      with:
        repository: pimoroni/pimoroni-pico
        ref: main
        path: pimoroni-pico

    # Checkout the Pico SDK
    - name: Checkout Pico SDK
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        ref: 2.1.1
        path: pico-sdk
        submodules: true

    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '13.3.Rel1'

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE/project -DMULTIVERSE_BOARD=${{matrix.board}} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCPACK_PACKAGE_FILE_NAME=${{env.RELEASE_FILE}} -DPIMORONI_PICO_PATH=$GITHUB_WORKSPACE/pimoroni-pico -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk -DPICO_BOARD=pico_w -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE -j 2

    - name: Store .uf2 as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.RELEASE_FILE}}.uf2
        path: ${{runner.workspace}}/build/${{matrix.board}}-multiverse.uf2

    - name: Build Release Packages
      if: github.event_name == 'release'
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE --target package -j 2

    - name: Upload .zip
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{runner.workspace}}/build/${{env.RELEASE_FILE}}.zip

    - name: Upload .tar.gz
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{runner.workspace}}/build/${{env.RELEASE_FILE}}.tar.gz
